### PR TITLE
fix: function score with no query serialisation

### LINKED ISSUE #257: Query builder return empty query instead of failing
The following query get serialized to an empty string, I guess the function_score is skipped during 
serialization.
```rust
    let query = Query::bool().should(
        Query::function_score()
            .boost_mode(FunctionBoostMode::Replace)
            .function(
                Function::decay(
                    DecayFunction::Gauss,
                    "coord",
                    GeoLocation::new(0.0, 0.0),
                    Distance::Meters(5000),
                )
                .offset(Distance::Meters(1000))
                .weight(0.5)
                .decay(0.3),
            ),
    );
```
the output json: 
```json
{
  "bool": {}
}
```

### PR DESCRIPTION
**Pull request by oknozor**
closes #257

### CODE REVIEW

**Review by buinauskas — DISMISSED** [review]

**Comment by buinauskas** [comment]
@oknozor please rebase on master, there was a rust version upgrade and it had some breaking linting changes which I had to fix.

**Comment by oknozor** [comment]
Done

**Comment by buinauskas** [comment]
@oknozor something's off with the CI build. I do see that your code is up to date but CI build workflow complains about the lint rule. How hard for you would it be to resubmit this PR fresh?

That's the workflow output https://github.com/vinted/elasticsearch-dsl-rs/actions/runs/6927980708/job/18845978149#step:6:24

**Comment by oknozor** [comment]
moved to https://github.com/vinted/elasticsearch-dsl-rs/pull/260

**Pull request closed without merging**
