### PR TITLE
Add include and exclude to terms aggregation

### PR DESCRIPTION
**Pull request by dean-shaff**
Add include and exclude parameters to terms aggregation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4

### CODE REVIEW

**Review by buinauskas — DISMISSED** [review]
Thanks! I see that due to rust version upgrades, there are some ambiguities, let me update master and I'll ask you to rebase. 

How fast do you need this to be released?

**Comment by dean-shaff** [comment]
There is no rush whatsoever!

**Comment by buinauskas** [comment]
@dean-shaff cool, so make sure to rebase on latest first and then submit the change if possible. There were some breaking changes in Rust 1.73.0 that required updating the code. Otherwise, CI tests would fail.

**Comment by buinauskas** [comment]
@dean-shaff sorry, I've been away and could only come back to this now. Could you split this PR into two? One for collapse, the other one for includes/excludes in terms aggregation?

**Comment by buinauskas** [comment]
Closing, implemented in two separate PRs.

**Pull request closed without merging**
